AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for text2video application with S3 buckets, ALB, API Gateway, Lambda functions, and DocumentDB'

Resources:
  # S3 Buckets
  ModelsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'models'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  Text2VideoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'text2video'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

Outputs:
  ModelsBucketName:
    Description: Name of the models S3 bucket
    Value: !Ref ModelsBucket

  Text2VideoBucketName:
    Description: Name of the text2video S3 bucket
    Value: !Ref Text2VideoBucket
